[versions]
loom = "1.14-SNAPSHOT"
fletchingTable = "0.1.0-alpha.22"
ksp = "2.3.0"
kotlin = "2.3.0"

devauth = "1.2.1"
commodore = "1.0.1"

fabric-loader = "0.17.3"
fabric-language-kotlin = "1.13.8+kotlin.2.3.0"

fabric-api-1-21-8 = "0.136.1+1.21.8"
fabric-api-1-21-10 = "0.138.3+1.21.10"

odin-1-21-8 = "0.1.2-1.21.8"
odin-1-21-10 = "0.1.2-1.21.10"

# needed by odin to work properly in dev env as we use modrinth which doesn't provide the transitive dependencies
okhttp = "5.2.1"
okio = "3.16.1"
lwjgl-nanovg = "3.3.3"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
commodore = { module = "com.github.stivais:Commodore", version.ref = "commodore" }

fabric-api-1-21-8 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-1-21-8" }
fabric-api-1-21-10 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-1-21-10" }

odin-1-21-8 = { module = "maven.modrinth:odin", version.ref = "odin-1-21-8" }
odin-1-21-10 = { module = "maven.modrinth:odin", version.ref = "odin-1-21-10" }

# needed by odin to work properly in dev env as we use modrinth which doesn't provide the transitive dependencies
okhttp = { module = "com.squareup.okhttp3:okhttp-jvm", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio-jvm", version.ref = "okio" }
lwjgl-nanovg = { module = "org.lwjgl:lwjgl-nanovg", version.ref = "lwjgl-nanovg" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }
fletchingTable = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingTable" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }